INSERT INTO CategoriasCabys  VALUES (0,'Productos de la agricultura, silvicultura y pesca')
INSERT INTO CategoriasCabys  VALUES (1,'Minerales; electricidad, gas y agua')
INSERT INTO CategoriasCabys  VALUES (2,'Productos alimenticios, bebidas y tabaco; textiles, prendas de vestir y productos de cuero')
INSERT INTO CategoriasCabys  VALUES (3,'Bienes transportables, excepto productos metálicos, maquinaria y equipo, n.c.p.')
INSERT INTO CategoriasCabys  VALUES (4,'Productos metálicos, maquinaria y equipo')
INSERT INTO CategoriasCabys  VALUES (5,'Construcciones y servicios de construcción')
INSERT INTO CategoriasCabys  VALUES (6,'Servicios de venta y distribución; alojamiento; servicios de suministro de comidas y bebidas; servicios de transporte; servicios de distribución de electricidad, gas y agua')
INSERT INTO CategoriasCabys  VALUES (7,'Servicios financieros y servicios conexos; servicios inmobiliarios; servicios de arrendamiento financiero (leasing)')
INSERT INTO CategoriasCabys  VALUES (8,'Servicios prestados a las empresas y servicios de producción')
INSERT INTO CategoriasCabys  VALUES (9,'Servicios para la comunidad, sociales y personales')
